#' Synthetic SME lending development sample
#'
#' A synthetic development sample of accepted SME loan applications
#' with fully observed 12-month outcomes, generated with a documented
#' ground truth by \code{data-raw/sme_datagen.R}. All names, sectors,
#' branches, and values are fictitious, modelled on Bangladeshi SME
#' lending patterns.
#'
#' Bad is defined as 90+ days past due within 12 months of
#' disbursement, the standard application-scorecard performance
#' definition (Siddiqi, 2006). The realized bad rate is approximately
#' 10 percent.
#'
#' Missingness is informative by design: \code{bureau_score} is NA
#' for thin-file applicants; \code{dscr} and \code{current_ratio}
#' are jointly NA where financial statements were unaudited;
#' \code{ltv} is structurally NA for unsecured facilities.
#'
#' @format A tibble with 5,000 rows and 21 variables:
#' \describe{
#'   \item{loan_id}{Unique loan identifier, format SW-NNNNNN.}
#'   \item{app_month}{Origination cohort month, 2023-01 to 2024-12.}
#'   \item{sector}{Borrower sector: Trading, Manufacturing, Services,
#'     Agro-processing, Construction, Transport & Logistics.}
#'   \item{business_age}{Years since firm establishment.}
#'   \item{employees}{Firm headcount.}
#'   \item{annual_sales}{Declared annual turnover, BDT.}
#'   \item{check_returns_12m}{Dishonoured cheques in the previous
#'     12 months.}
#'   \item{bureau_score}{Credit bureau score, 300-900; NA for
#'     thin-file applicants.}
#'   \item{rm_tenure}{Years of relationship with the lender.}
#'   \item{loan_purpose}{Working Capital, Machinery Purchase,
#'     Business Expansion, or Trade Finance.}
#'   \item{branch}{Originating branch.}
#'   \item{loan_amount}{Sanctioned amount, BDT.}
#'   \item{tenor_months}{Loan tenor: 12, 24, 36, 48, or 60 months.}
#'   \item{collateral_type}{Primary collateral: Residential Property,
#'     Commercial Property, Machinery, Inventory, FDR, or Unsecured.}
#'   \item{ltv}{Loan-to-value ratio; NA when unsecured.}
#'   \item{rate_pct}{Annual pricing rate, percent.}
#'   \item{dscr}{Debt service coverage ratio; NA where statements
#'     unaudited.}
#'   \item{current_ratio}{Current assets over current liabilities;
#'     missing jointly with dscr.}
#'   \item{ever_90dpd_12m}{Bad flag: 1 if the loan reached 90+ DPD
#'     within 12 months of disbursement.}
#'   \item{months_to_default}{Month of first 90+ DPD, 3-12; 12 when
#'     no default occurred.}
#'   \item{status_12m}{Performing, Defaulted, or Early-settled.}
#' }
#' @source Generated by \code{data-raw/sme_datagen.R} with a fixed
#'   seed; the script documents the full data generating process.
"sme_dev_sample"

#' Synthetic SME scoring-period snapshots
#'
#' Six monthly snapshots of new SME loan applications, 2026-01 to
#' 2026-06, 400 applications each, generated through the same
#' mechanism chain as the development sample. Snapshots carry
#' application characteristics only; 12-month outcomes are not yet
#' mature, which is the situation population-stability monitoring is
#' designed for.
#'
#' @format A tibble with 2,400 rows and 18 variables:
#' \describe{
#'   \item{loan_id}{Unique loan identifier, format SW-NNNNNN,
#'     continuing the development-sample sequence.}
#'   \item{app_month}{Snapshot month, 2026-01 to 2026-06.}
#'   \item{sector}{Borrower sector, as in the development sample.}
#'   \item{business_age}{Years since firm establishment.}
#'   \item{employees}{Firm headcount.}
#'   \item{annual_sales}{Declared annual turnover, BDT.}
#'   \item{check_returns_12m}{Dishonoured cheques in the previous
#'     12 months.}
#'   \item{bureau_score}{Credit bureau score; NA for thin-file
#'     applicants.}
#'   \item{rm_tenure}{Years of relationship with the lender.}
#'   \item{loan_purpose}{Working Capital, Machinery Purchase,
#'     Business Expansion, or Trade Finance.}
#'   \item{branch}{Originating branch.}
#'   \item{loan_amount}{Sanctioned amount, BDT.}
#'   \item{tenor_months}{Loan tenor: 12, 24, 36, 48, or 60 months.}
#'   \item{collateral_type}{Primary collateral, as in the
#'     development sample.}
#'   \item{ltv}{Loan-to-value ratio; NA when unsecured.}
#'   \item{rate_pct}{Annual pricing rate, percent.}
#'   \item{dscr}{Debt service coverage ratio; NA where statements
#'     unaudited.}
#'   \item{current_ratio}{Current assets over current liabilities;
#'     missing jointly with dscr.}
#' }
#' @source Generated by \code{data-raw/sme_datagen.R} with a fixed
#'   seed; the script documents the full data generating process.
"sme_scoring_snaps"